language: java
sudo: false

cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk11
  - openjdk9
  - openjdk8

git:
  quiet: true

stages:
  - compile
  - test
  - name: deploy
    if: branch = master
